export const ENVIRONMENT = {
  REOWN_PROJECT_ID: process.env.NEXT_PUBLIC_REOWN_PROJECT_ID || "",
  ARBITRUM_SEPOLIA_RPC_URL:
    process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_RPC_URL || "",
  ETHEREUM_SEPOLIA_RPC_URL:
    process.env.NEXT_PUBLIC_ETHEREUM_SEPOLIA_RPC_URL || "",
  L1_PROXY_ADDRESS: (process.env.NEXT_PUBLIC_L1_PROXY_ADDRESS || "0x") as "0x",
};
